In [96]:
import numpy as np
import nn; reload(nn)

<module 'nn' from 'nn.py'>

In [99]:
network = nn.Network([4, 3, 4])

In [112]:
inputs = np.reshape([1,0,3,4], (4, 1))

In [104]:
inputs

array([[1],
       [2],
       [3],
       [4]])

In [113]:
network.forward(inputs)

array([[ 0.99975622],
       [ 0.95378825],
       [ 0.97810341],
       [ 0.99943159]])

In [114]:
a = np.reshape([1,2,3,4], (2,2))

In [115]:
a

array([[1, 2],
       [3, 4]])

In [123]:
b = np.reshape([0, 0, 0, 0], (2,2))
b

array([[0, 0],
       [0, 0]])

In [124]:
np.square(a - b).sum()

30