In [2]:
import numpy as np
import nn; reload(nn)

<module 'nn' from 'nn.pyc'>

In [99]:
network = nn.Network([4, 3, 4])

In [112]:
inputs = np.reshape([1,0,3,4], (4, 1))

In [104]:
inputs

array([[1],
       [2],
       [3],
       [4]])

In [113]:
network.forward(inputs)

array([[ 0.99975622],
       [ 0.95378825],
       [ 0.97810341],
       [ 0.99943159]])

In [4]:
a = np.reshape([1,2,3,4], (2,2))

In [115]:
a

array([[1, 2],
       [3, 4]])

In [9]:
b = np.reshape([5, 6, 7, 8], (2,2))
b

array([[5, 6],
       [7, 8]])

In [ ]:
np.square(a - b).sum()

In [10]:
a * b

array([[ 5, 12],
       [21, 32]])