In [33]:
import numpy as np
import random

In [2]:
np.random.randn(10,1)

array([[-0.55951909],
       [-1.49691752],
       [ 0.44242601],
       [ 0.95085926],
       [ 0.40761725],
       [-1.54147809],
       [-0.791315  ],
       [-0.72185889],
       [-0.01366382],
       [ 1.04120214]])

In [3]:
sizes = [1,2,3,4,5]

In [4]:
sizes[:-1]

[1, 2, 3, 4]

In [7]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [17]:
a = np.random.randn(3)
a

array([-0.06292475, -0.89705185, -0.25690517])

In [18]:
sigmoid(a)

array([0.484274  , 0.28965672, 0.43612464])

In [47]:
w = np.array([[1,2,3], [4,5,6]])
w

array([[1, 2, 3],
       [4, 5, 6]])

In [49]:
a = np.array([[1], [2], [3]])
# a = np.array([1,2,3])
a

array([[1],
       [2],
       [3]])

In [45]:
np.dot(w, a)

array([14, 32])

In [53]:
lst = [1,2,3,4]

In [60]:
random.shuffle(lst)

In [61]:
lst

[2, 1, 4, 3]

In [68]:
for a in range(1,12,3):
    print(a)

1
4
7
10


In [75]:
arr = [1,2,3,4,5]
arr[0:4]

[1, 2, 3, 4]

In [80]:
"{0} haha {1}".format(1, "ab")

'1 haha ab'

In [86]:
arr[-5]

1

In [25]:
import mnist_loader

In [26]:
training_data, validation_data, test_data = mnist_loader = mnist_loader.load_data_wrapper()

In [27]:
lst = list(training_data)

In [31]:
lst[0][0].shape

(784, 1)

In [34]:
a = np.array([[1,2], [3,4]])
a

array([[1, 2],
       [3, 4]])

In [35]:
b = np.array([[1,2], [3,4]])
b

array([[1, 2],
       [3, 4]])

In [40]:
np.multiply(a,b)

array([[ 1,  4],
       [ 9, 16]])

In [41]:
a.dot(b)

array([[ 7, 10],
       [15, 22]])