In [1]:
import tensorflow as tf
import numpy as np

# 网络结构: 2维输入 --> 2维隐藏层 --> 1维输出
# 学习速率 (learning rate): 0.0001
D_input = 2
D_label = 1
D_hidden = 2
lr = 1e-4

# 容器
x = tf.placeholder(tf.float32, [None, D_input], name="x")
t = tf.placeholder(tf.float32, [None, D_label], name="t")

# 隐藏层
# 初始化 W
W_h1 = tf.Variable(tf.truncated_normal([D_input, D_hidden], stddev=0.1), name="W_h")
# 初始化 b
b_h1 = tf.Variable(tf.constant(0.1, shape=[D_hidden]), name="b_h")
# 计算 Wx+b
pre_act_h1 = tf.matmul(x, W_h1) + b_h1
# 计算 a(Wx+b)
act_h1 = tf.nn.relu(pre_act_h1, name="act_h")

# 输出层
W_o = tf.Variable(tf.truncated_normal([D_hidden, D_label], stddev=0.1), name="W_o")
b_o = tf.Variable(tf.constant(0.1, shape=[D_label]), name="b_o")
pre_act_o = tf.matmul(act_h1, W_o) + b_o
y = tf.nn.relu(pre_act_o, name="act_y")

# 反向传递
# 损失函数
loss = tf.reduce_mean((y - t)**2)
train_step = tf.train.AdamOptimizer(lr).minimize(loss)

In [20]:
# 准备数据
# X 和 Y 是 4 个数据的矩阵, X[i] 和 Y[i] 的值始终对应
X = [ [0, 0], [0, 1], [1, 0], [1, 1] ]
Y = [ [0], [1], [1], [0] ]
X = np.array(X).astype('int16')
Y = np.array(Y).astype('int16')

In [32]:
X[0]

array([0, 0], dtype=int16)

In [37]:
# 创建 session
sess = tf.InteractiveSession()
# 初始化权重
tf.initialize_all_variables().run()

# 训练次数
T = 100000
for i in range(T):
    if i % 10000 == 0:
        print(i)
    #for j in range(X.shape[0]):
    sess.run(train_step, feed_dict={x: X, t: Y})

Instructions for updating:
Use `tf.global_variables_initializer` instead.
0
10000
20000
30000
40000
50000
60000
70000
80000
90000


In [64]:
# 计算预测值
i = 3
print(X[i])
sess.run(y, feed_dict={x: np.reshape(X[i], [1,2])})

[1 1]


array([[ 0.]], dtype=float32)

In [60]:
# 查看隐藏层输出
sess.run(act_h1, feed_dict={x: np.reshape(X[1], [1,2])})

array([[ 0.        ,  0.89560884]], dtype=float32)