In [1]:
import torch

In [11]:
t = torch.rand(2, 4, 4)
b = t.view(-1, t.size(0))

In [12]:
t

tensor([[[0.2097, 0.7593, 0.2723, 0.4139],
         [0.6391, 0.9272, 0.2340, 0.3162],
         [0.8561, 0.6301, 0.2410, 0.5236],
         [0.5418, 0.3124, 0.4287, 0.9761]],

        [[0.3945, 0.5968, 0.0949, 0.1971],
         [0.8427, 0.4897, 0.0428, 0.0020],
         [0.2889, 0.1361, 0.0190, 0.2010],
         [0.7765, 0.7752, 0.5001, 0.9041]]])

In [13]:
b

tensor([[0.2097, 0.7593],
        [0.2723, 0.4139],
        [0.6391, 0.9272],
        [0.2340, 0.3162],
        [0.8561, 0.6301],
        [0.2410, 0.5236],
        [0.5418, 0.3124],
        [0.4287, 0.9761],
        [0.3945, 0.5968],
        [0.0949, 0.1971],
        [0.8427, 0.4897],
        [0.0428, 0.0020],
        [0.2889, 0.1361],
        [0.0190, 0.2010],
        [0.7765, 0.7752],
        [0.5001, 0.9041]])

In [10]:
t.view?

In [14]:
import torch.nn.functional as F

In [17]:
x = torch.tensor([4,3,2,1,0])
F.one_hot(x, num_classes=10)

tensor([[0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
        [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
        [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
        [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0, 0, 0, 0, 0]])